### ISSUE TITLE
Can't use MatiSDK 3.x.x.

### ISSUE THREAD

**Issue by Desmuz** [GetMati/mati-ios-sdk#10]
When I try use MatiSDK (last version from pods, at 10.05.2021):

<project_path>/Pods/Mati-Global-ID-SDK/MatiSDK.framework/Modules/MatiSDK.swiftmodule/arm64-apple-ios.swiftinterface:11:8: Compiling for iOS 11.4, but module 'SocketIO' has a minimum deployment target of iOS 12.0: <project_path>/DerivedData/<project>/Build/Products/Debug-iphoneos/Socket.IO-Client-Swift/SocketIO.framework/Modules/SocketIO.swiftmodule/arm64-apple-ios.swiftmodule

Failed to build module 'MatiSDK' from its module interface; the compiler that produced it, 'Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)'

**Comment by aposnov** [comment]
@Desmuz Hello, do you have any other logs?

**Comment by aposnovmati** [comment]
@Desmuz Hello, please try latest version 3.2.1
