### ISSUE TITLE
Default language set

### ISSUE THREAD

**Issue by applesubir** [GetMati/mati-ios-sdk#11]
Hi,
     I am facing one thing, that's not able to set default preferable language. 
So Please help me how to set default language when Mati button is initialise. 

 Thanks.

**Comment by aposnovmati** [comment]
Hello @applesubir we dont have this functional yet, but default language should set by device locale, we plan to add this in future releases

**Comment by applesubir** [comment]
hi,
  i am also not able to choose identity card.
Only getting option Driver's License.

**Comment by aposnovmati** [comment]
@applesubir Hello, we added this in latest 3.2.1 version, please try it, for details please use our docs https://github.com/GetMati/mati-ios-sdk
