### ISSUE TITLE
Unable to choose identity card.

### ISSUE THREAD

**Issue by applesubir** [GetMati/mati-ios-sdk#12]
hi,
i am not able to choose identity card.
Only getting option Driver's License.
Sdk version: 3.0.3

**Comment by aposnovmati** [comment]
Hello @applesubir please update version to 3.1.0

**Comment by applesubir** [comment]
when I am pod install with version 3.1.0

[!] CocoaPods could not find compatible versions for pod "Mati-Global-ID-SDK":
  In Podfile:
    Mati-Global-ID-SDK (~> 3.1.0)

None of your spec sources contain a spec satisfying the dependency: `Mati-Global-ID-SDK (~> 3.1.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
 
Please tell me what I do

**Comment by aposnovmati** [comment]
@applesubir Hello, please try latest version 3.2.1
