### ISSUE TITLE
'MatiButtonResultDelegate' is not a member type of 'MatiSDK'

### ISSUE THREAD

**Issue by applesubir** [GetMati/mati-ios-sdk#13]
Please help me.

**Comment by aposnovmati** [comment]
@applesubir Hello, could you share yours code screenshot?

**Comment by aposnovmati** [comment]
@applesubir error still actual?

**Comment by applesubir** [comment]
yes, still facing that error.

**Comment by johnsonejezie** [comment]
<img width="1418" alt="Screenshot 2021-06-17 at 16 20 48" src="https://user-images.githubusercontent.com/8383735/122395423-05847200-cf88-11eb-8e3d-6e737d6e4822.png">

**Comment by GustavoAlvarez** [comment]
Here is another screenshot, I got 354 errors!
![image](https://user-images.githubusercontent.com/10645951/124785355-67435680-df0c-11eb-8b38-d48ff2786fb2.png)

**Comment by aposnovmati** [comment]
@GustavoAlvarez @johnsonejezie @applesubir try to re-install pods, with pod clean command, and then pod install

**Comment by GustavoAlvarez** [comment]
@aposnovmati Already did that 3 times and still the same errors

**Comment by aposnovmati** [comment]
@GustavoAlvarez what iOS version do you using?

**Comment by GustavoAlvarez** [comment]
I found what's wrong, you are using swift 5.4, and I'm using 5.3.2. I think you should mention every time you change Swift/Xcode and IOS version.

**Comment by aposnovmati** [comment]
Hello @GustavoAlvarez we didnt change swift version, did you use native sdk or crossplatfrom plugin?

**Comment by GustavoAlvarez** [comment]
Native SDK

**Comment by applesubir** [comment]
Hello,
 
![Screenshot 2021-07-29 at 10 18 46 PM](https://user-images.githubusercontent.com/84585210/127532485-6c74c2b8-4536-4ab7-ad13-b7d0c181af31.png)
Please tell me what should I do

**Comment by applesubir** [comment]
SDK version - 3.2.2

**Comment by aposnovmati** [comment]
Hello @applesubir please use Xcode 12.5, why investigating why it doesn’t work for Xcode 12.4

**Comment by applesubir** [comment]
will it solve if I use Xcode 12.5 ?

**Comment by aposnovmati** [comment]
@applesubir yes 100%

**Comment by applesubir** [comment]
Let's try

**Comment by GustavoAlvarez** [comment]
Have you tried compiling your SDK with Xcode 12.4?

**Comment by applesubir** [comment]
Update not available for me.

**Comment by applesubir** [comment]
> Have you tried compiling your SDK with Xcode 12.4?

yes, have any solution with Xcode 12.4 ?

**Comment by aposnovmati** [comment]
@applesubir sorry, why cant use new Xcode 12.5? For Xcode 12.4 we still investigating solution, hope will be provided early next week

**Comment by applesubir** [comment]
I have macOS Catalina.
![Screenshot 2021-07-30 at 12 20 21 PM](https://user-images.githubusercontent.com/84585210/127613113-76d907c1-d81a-4148-a705-d45db5ab6adc.png)

**Comment by mousumi-appnistic** [comment]
@aposnovmati we were using iOS SDK v3.1.4...from yesterday app it not working ....after contacting support team ..get to know that version is outdated ...Now we can't use latest sdk due Xcode issue .......
What is the solution now ? 
Can you pls help ?

**Comment by aposnovmati** [comment]
@applesubir ok, understood. As I wrote above, we still investigating a solution, hope will be provided early next week
@mousumi-appnistic You can't update Xcode either?
**We will try to find a solution today**, but the deadline is **early next week**

**Comment by mousumi-appnistic** [comment]
@aposnovmati Xcode update is available yet in my OS  (macOS Catalina ).

**Comment by aposnovmati** [comment]
@applesubir @mousumi-appnistic @GustavoAlvarez @johnsonejezie  Hello all, please try the new 3.3.1 version, i will wait for feedback

**Comment by applesubir** [comment]
Thanks, @aposnovmati

**Comment by GustavoAlvarez** [comment]
It works now, thanks!

**Comment by aposnovmati** [comment]
@applesubir @GustavoAlvarez thanks a lot for patience, if you will have any questions/issues please open new ticket
