### ISSUE TITLE
App is not compiling due to iOS SDK update

### ISSUE THREAD

**Issue by pablobonillaglobant** [GetMati/mati-ios-sdk#14]
Hi team!

I tried some days ago to update iOS SDK version from 2.8.0 to 3.1.0, update everything necessary and clean cache but the app could not compiling showing this message:

The following build commands failed:
        CompileC /Users/pablo.bonilla/Library/Developer/Xcode/DerivedData/TuPanaApp-ccwezaylbqtjinftxqpzrqiguodp/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-mati-global-id-sdk.build/Objects-normal/x86_64/MatiGlobalIdSdk.o /Users/pablo.bonilla/Documents/TuPana/tupana-front-mobile-app/node_modules/react-native-mati-global-id-sdk/ios/MatiGlobalIdSdk.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

 Also add a screenshot when tried to use it by Xcode:

![CD95C52C-E6D8-452B-BB67-D3A6EE54D218](https://user-images.githubusercontent.com/86698428/124003894-0c09e500-d99d-11eb-8fe5-6414244ec236.png)

Can you help me to know the reason of this error? Is something missing?

Thanks a lot!

**Comment by aposnovmati** [comment]
@pablobonillaglobant Hello, please try to update to 3.2.2 (latest version)
