### ISSUE TITLE
Metadata with Int Value isn't going thru

### ISSUE THREAD

**Issue by dfmarulanda** [GetMati/mati-ios-sdk#17]
Hello.
When I send metadata with an integer value, instead of a string, isn't going thru mati.

**Comment by aposnovmati** [comment]
Hello @dfmarulanda yes, it can be, let me check, 1) do you want to use Int for key or for value? 2) it is for iOS SDK right?

**Comment by dfmarulanda** [comment]
Int value. In Android works well

**Comment by aposnovmati** [comment]
Hello @dfmarulanda got it, yes in iOS we have [String:String?] let me prepare an update to change into [String:Any?], i think we can provide update till this Friday

**Comment by aposnovmati** [comment]
@dfmarulanda Hello, we have just published 3.3.3 please try it

**Comment by aposnovmati** [comment]
If you will have new questions/issues, please open a new ticket
