### ISSUE TITLE
Add SPM Support 

### ISSUE THREAD

**Issue by pierosifuentesp** [GetMati/mati-ios-sdk#21]
#### Issue description

Missing support to SPM

#### Steps to reproduce the issue

1.  Open Xcode and add a new SPM dependency 
2. Set Mati Github as new dependency  https://github.com/GetMati/mati-ios-sdk
3. Tap add package and wait

#### What's the expected result?

- Mati installed through SPM

#### What's the actual result?

- Package resolution failed

#### Additional details / screenshot

- ![image](https://user-images.githubusercontent.com/79066778/132577290-851ec1df-09c6-4f9b-8369-7574b9035517.png)

**Comment by aposnovmati** [comment]
Hello, we have just added support SPM, please choose "master" while adding Mati SDK
example https://drive.google.com/file/d/146wEIBQj_wCysWUAbMQfXeO6OALbdXEt/view?usp=sharing

If you will have more questions please open new ticket
