### ISSUE TITLE
Missing documentation validation process.

### ISSUE THREAD

**Issue by DiegoVazSan** [GetMati/mati-ios-sdk#27]
The first time you download the app with Mati installed, **the steps to scan documents are skipped** and go directly to the next validation. (voice validation)

attached evidence:
[https://drive.google.com/file/d/12vloBV_yC3_oMgeWO5Afje8ZcrF0luk6/view?usp=sharing](url)

**Comment by AvoSukiasyan** [comment]
Hi @DiegoVazSan. thank you so much for comment.
I want to clarify it was custom document or document verification and also can you say which is the flow was before document verification ?

**Comment by DiegoVazSan** [comment]
Hi Avo_Sukiasyan, Excellent day, thank you for your attendance, sure,I was
mean with the "document verification" to Mati's flow  wich  Mati ask you
for your ID card and licence to drive to verify you as user, said flow is
skipped, So this should be the first Mati's flow in our
project, Nevertheless, when you start the app at first time, this flow is
not presented.
We welcome your support in advance, I hope this message be enough for you,
If I can help you with something else, please let me know.
We will be paying attention to anything.
Thank you very much, have a coordial greeting !

**Comment by AvoSukiasyan** [comment]
I tried to reproduce this issue but in my example project it's work correctly. 
can you say which SDK version do you use ?

https://user-images.githubusercontent.com/43985438/140764956-8ec5ffdb-20e0-461b-ab60-546f4837192b.MP4

**Comment by DiegoVazSan** [comment]
Sure, here it is.
Our current version is 3.7.7
Likewise, I share a video showing the issue.
Thank you very much for your support , greetings to all of you!
https://drive.google.com/file/d/12vloBV_yC3_oMgeWO5Afje8ZcrF0luk6/view?usp=sharing

**Comment by AvoSukiasyan** [comment]
Yeah it's related to the camera and microphone permission. 
After allow permission the first step is skipping that why it's happening only first time. 
We'll fix it and it will be available in the next version of the SDK. 
thanks @DiegoVazSan .

**Comment by AvoSukiasyan** [comment]
Hi @DiegoVazSan . the issue fixed . please update version to 3.7.8.

**Comment by DiegoVazSan** [comment]
Hi Avo_Sukiasyan , thank you very much for Your support for this Issue, I
will make the necesary tests for validate this issue

greetings to all !
