### ISSUE TITLE
Unable to build MatiSDK in Apple M1 Max

### ISSUE THREAD

**Issue by aravasio** [GetMati/mati-ios-sdk#28]
Hello,

I'm trying to build my company's project in a new MBP 16" with an M1 Max chip. Xcode 13.1. MacOS Monterey.

Originally, the project was using`'https://github.com/GetMati/mati-ios-sdk', :tag => '3.2.3'`, but that version was outputting A LOT of this kind of error: 

`'MatiButtonResultDelegate' is not a member type of class 'MatiSDK.MatiSDK'`

<img width="453" alt="Screen Shot 2021-11-14 at 23 30 33" src="https://user-images.githubusercontent.com/7585675/141713017-99c6f935-978e-4af7-aaf5-626ed6bfd78d.png">

Now, when I move forward enough in the release history to the latest version (currently, `3.7.8`), the error shifts to:
`Module 'MatiSDK' has no member named 'shared'`

as if something changed in the codebase, but I can't find any documentation about it (available docs still use `.shared` to showcase how to use Mati).

Any help is greatly appreciated.

**Comment by aravasio** [comment]
Managed to get it to build using the following conditions:

```
Xcode 12.5.1
MatiSDK 3.2.3
```

Sadly, since this is MacOS Monterey, XC versions under 13 basically break compatibility, so I had to use the "run xcode from terminal" trick.

Also, any version of MatiSDK other than 3.2.3 seems to fail. 3.3.0+ _still_ generates the `.shared` issue.

**Comment by AvoSukiasyan** [comment]
HI @aravasio.  I believe the issue related Xcode settings. it's Xcode 12 issue Could not find module 'FrameworkName' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_64". 
you can update Xcode version to 13 and i think it's solved this problem or if you don't want to update try this https://stackoverflow.com/questions/64026065/xcode-12-issue-could-not-find-module-frameworkname-for-target-arm64-apple-i

**Comment by aravasio** [comment]
Hi, thanks for the answer. Just to make sure, I had this issue in xc 13, not xc 12.

In xc12 I managed to get it to build just fine, it's xc13 that's giving me issues right now.

**Comment by AvoSukiasyan** [comment]
@aravasio please replace MatiSDK to Mati .  like this - Mati.shared.showMatiFlow
And also please  try to build on real device just for test.

**Comment by AvoSukiasyan** [comment]
@aravasio HI . is it work for you already?

**Comment by aravasio** [comment]
@AvoSukiasyan hey. Sorry for the delay in responding.

yes, it seems the change was to the “MatiSDK” to “Mati” space. Now it works perfectly on the latest versions.

thanks!
