### ISSUE TITLE
Infinity indicator in MFKYCButton

### ISSUE THREAD

**Issue by Desmuz** [GetMati/mati-ios-sdk#8]
Recently (since the last pod update) the button displays a progress indicator.

In appDelegate:
MFKYC.register(clientId:"my clientId")

In controller:
MFKYC.instance.delegate = self
MFKYC.instance.metadata = ["email": email]

let matiButton = MFKYCButton()
matiButton.title = "Verify me"
matiButton.frame = frame
addSubview(matiButton)

Can anyone help me with this?

**Comment by aposnov** [comment]
@Desmuz Hello, do you use one button or several?

**Comment by Desmuz** [comment]
> @Desmuz Hello, do you use one button or several?

Only one.

**Comment by aposnov** [comment]
@Desmuz Do you use the latest version 2.8.1?

**Comment by Desmuz** [comment]
Yes, I have used pods before, but I downloaded the latest version of the framework and only the button color has changed.

**Comment by Desmuz** [comment]
![Screenshot 2020-10-27 at 00 01 15](https://user-images.githubusercontent.com/73358057/97203584-9a631100-17e7-11eb-94c1-adfa3da6e1ee.png)

**Comment by aposnovmati** [comment]
@Desmuz could you please share part of your code? you can send it to me by email andrey.posnov@mati.io

**Comment by aposnov** [comment]
@Desmuz please move MFKYC.register(clientId:"my clientId") from appdelegate to yours controller

**Comment by Desmuz** [comment]
Thanks, it helped. But now endless loading happens if you exit (cancel) from the Mati controller.

**Comment by DevMobileWalabi** [comment]
Hi good day.
I have had the same problem with the activity indicator, I already moved MFKYC.register(clientId:"my clientId") code to my controller. The button sometimes finishes loading and sometimes not.
I currently use version 2.9.1

**Comment by aposnovmati** [comment]
Hello, @Desmuz and @DevMobileWalabi please update to the latest version 3.0.1, and tell us if the issue still actual or not

**Comment by ccparram** [comment]
I'm using version 3.0.2 and get the same issue, last week was working fine.

![image](https://user-images.githubusercontent.com/2968424/112089167-18d99a00-8b5f-11eb-92a5-62aa1a55546b.png)

**Comment by aposnovmati** [comment]
@ccparram  Hello, it was fixed in 3.0.3, please try the lates version
